[[main]]
name = "Home"
url = ""
weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
identifier = "Links"
name = "Links"
weight = -108
[[main]]
name = "LinkedIn"
parent = "Links"
url = "https://www.linkedin.com/in/sma%C3%AFne-kahlouch-44374110/"
[[main]]
name = "Bluesky"
parent = "Links"
url = "https://bsky.app/profile/smana.dev"

[[main]]
name = "About"
url = "about/"
weight = -107

# social menu links

[[social]]
name = "github"
type = "social"
url = "https://github.com/Smana"
weight = 1
[[social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sma%C3%AFne-kahlouch-44374110/"
weight = 3
[[social]]
name = "bluesky"
url = "https://bsky.app/profile/smana.dev"
